import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import Header from "@/components/Header.jsx";
import { Input } from "@/components/ui/input";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Input/>
        <Header/>
        {children}
        <Toaster toastOptions={{duration:1000}} />
      </body>
    </html>
  );
}
